# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

Uninstall-BinFile "d"
Uninstall-BinFile "h"
Uninstall-BinFile "r"
Uninstall-BinFile "s"
Uninstall-BinFile "rs"
Uninstall-BinFile "rh"
